### ISSUE TITLE
SetVirtualSelectConfigs does not include all of the provider's config options

### ISSUE THREAD

**Issue by alexandre97costa** [OutSystems/outsystems-ui#815]
The [list of properties made available by the provider](https://sa-si-dev.github.io/virtual-select/#/properties) does not match with the current available options to configure in the SetVirtualSelectConfigs Client Action. Most importantly, the option to disable search is not present.

**Comment by gnbm** [comment]
@alexandre97costa This is by design. Also, from a product standpoint, a component called Dropdown Search doesn't make sense to have an option to remove the search (otherwise would be a simple dropdown widget that already exists in the platform). 
However, with the use of high code that can still be achieved even though we don't advise it.
